name: uni_color_name
description: >-
  Identifies the value of a color by name and vice versa. Knows over 900 color names.
  The easy-to-use and well-tested library.
repository: https://github.com/signmotion/uni_color_name
topics:
  - identify
  - color
  - palette
  - detector
  - image

# Format:
#   version: major.minor.patch
# You can calculate the number version code by this formula:
#   code = m[A]jor * 100 * 100 + m[I]nor * 100 + [P]atch
# Otherwise: +AAIIPP
version: 0.5.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  wfile: ^0.4.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2

screenshots:
  - description: "UniColorName demo"
    path: images/screenshots/zeplin_palette.webp
